zline_generate_config() {
  local style="${1:-powerline}"
  local transient="${2:-1}"
  local shorten="${3:-1}"
  local anchor="${4:-git}"

  local trans_flag=""
  (( transient == 1 )) && trans_flag=" --transient"

  local anchor_flag=""
  [[ "$anchor" == "git" ]] && anchor_flag=" --anchor git"

  REPLY="# Generated by zline configure
zline preset ${style}${trans_flag}

zline_left=(
  'dir --shorten ${shorten}${anchor_flag}'
  'git --clean 2 --dirty 3'
  newline
  prompt_char
)

zline_right=(
  'status --hide-zero'
  'exec_time --min 2'
)

zline init"
}

zline_configure() {
  local -A opts=()
  local -a flags=()
  zparseopts -E -D -A opts -K \
    -style:=opts -shorten:=opts -anchor:=opts -out:=opts \
    -transient=flags -no-transient=flags

  local style="${opts[--style]:-powerline}"
  local -i transient=1
  (( ${flags[(Ie)--no-transient]} > 0 )) && transient=0
  local -i shorten="${opts[--shorten]:-1}"
  local anchor="${opts[--anchor]:-git}"
  local out_file="${opts[--out]}"

  if [[ -z "$out_file" && ! -t 0 ]]; then
    out_file="${HOME}/.zline.zsh"
  fi

  if [[ -n "$out_file" ]]; then
    zline_generate_config "$style" "$transient" "$shorten" "$anchor"
    print -r -- "$REPLY" >! "$out_file"
    print -P "  %F{10}✓%f Saved configuration to %B${out_file}%b"
    return 0
  fi

  print -P "%F{14}%B============================================================%b%f"
  print -P "%F{15}%B              zline Interactive Configuration               %b%f"
  print -P "%F{14}%B============================================================%b%f\n"

  print -P "1. Select visual preset:"
  print "   1) Powerline (classic background blocks & arrows)"
  print "   2) Lean (modern, flat, space-separated)"
  print "   3) Rainbow (vivid high-contrast blocks)"
  print "   4) Pure (minimalist two-line layout)"
  print -n "   Choice [1-4, default 1]: "
  read -r choice_preset
  case "$choice_preset" in
    2) style="lean" ;;
    3) style="rainbow" ;;
    4) style="pure" ;;
    *) style="powerline" ;;
  esac

  print -P "\n2. Enable transient prompt (collapse on Enter)?"
  print -n "   [y/n, default y]: "
  read -r choice_trans
  [[ "$choice_trans" == [nN]* ]] && transient=0

  print -P "\n3. Select path shortening strategy:"
  print "   1) Shorten intermediate dirs + anchor Git root (e.g. ~/s/g/c/zline)"
  print "   2) Shorten intermediate dirs without anchor (e.g. ~/s/g/c/z)"
  print "   3) Full path (no shortening)"
  print -n "   Choice [1-3, default 1]: "
  read -r choice_dir
  case "$choice_dir" in
    2) shorten=1; anchor="none" ;;
    3) shorten=0; anchor="none" ;;
    *) shorten=1; anchor="git" ;;
  esac

  out_file="${HOME}/.zline.zsh"
  zline_generate_config "$style" "$transient" "$shorten" "$anchor"

  print -P "\n%F{15}%BPreview of generated configuration:%b%f\n"
  print -r -- "$REPLY"
  print -P "\nSave this configuration to %B${out_file}%b? [y/n]: "
  read -r confirm
  if [[ "$confirm" != [nN]* ]]; then
    print -r -- "$REPLY" >! "$out_file"
    print -P "\n%F{10}✓ Configuration saved to ${out_file}%f"
    print -P "To load this configuration, ensure the following is in your %B~/.zshrc%b:"
    print -P "  %F{14}source ${out_file}%f\n"
  else
    print -P "\n%F{11}Configuration not saved.%f"
  fi
}
